### ISSUE TITLE
Ember 2 compatibility

### ISSUE THREAD

**Issue by cimtico** [nibynic/ember-form-builder#3]
Are there any plans on getting this ember 2 compatible?
At the moment I'm getting an error regarding the usage of the "controller" reference.
If I pass something else, then I get an env.hooks.keywords.component.render is not a function on input-on.js line 16

**Comment by piotrekbator** [comment]
Yes, I'm planning to update this to be Ember 2.0 compatible. I plan to get rid of the keyword hacks and replace them with regular components making use of positional parameters (not available in 1.13) to make the `input-on f` syntax possible.

I hope I'll find some time to do that during the Christmas period. Will that be soon enough for you?

**Comment by piotrekbator** [comment]
@cimtico But wait, it **is** compatible with Ember 2.0 - just not perfectly. I have this addon working in two Ember 2.1 projects. Are you sure, you have the newest version installed? Try `npm update ember-simple-form` and restarting ember server.
